config/routes.rb
Rails.application.routes.draw do

  root "messages#index"
  resources :contacts
  resources :messages, :only => [:index, :show, :create, :new]
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :phonenumber
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_message
  validates_presence_of :to
  validates_presence_of :from
  validates_presence_of :body
  

private

  def send_message
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
                      :To => to,
                      :From => from }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  respond_to :html, :js

  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      respond_to do |format|
        format.html { redirect_to contacts_path }
        format.js { flash.now[:notice] = "Saved" }
      end
    else
      redirect_to contacts_path
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def edit
    @contact = Contact.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      respond_to do |format|
        format.html { redirect_to contacts_path }
        format.js { flash.now[:notice] = "Changes Saved" }
      end
    else
      redirect_to contact_path(@contact)
    end
  end

private

  def contact_params
    params.require(:contact).permit(:name, :phonenumber)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
    @contacts = Contact.all
  end

  def create
    # @contacts = Contact.all
    params_saved = params
    from = params[:from]
    body = params[:body]
    to = []


    if params_saved[:to].present?
      to = to.push(params_saved[:to]).first
      params = { to: to, from: from, body: body}
      @message = Message.new(params)
      if @message.save
        respond_to do |format|
          format.html { redirect_to messages_path }
          format.js { flash.now[:notice] = "Message Sent!!" }
        end
      else
        redirect_to messages_path
      end
    elsif params_saved[:contact_ids].any?
      params_saved[:contact_ids].each do |contact|
        found_contact = Contact.find(contact)
        to.push(found_contact.phonenumber)
      end
    end

    if to.class == Array && to.length > 1
      to.each do |t|
        Message.create({to: t, body: body, from: from})
      end
      respond_to do |format|
        format.html { redirect_to messages_path }
        format.js { render :messages_sent }
      end

    end

  end

  def show
    @message = Message.find(params[:id])
  end

# private
#
#   def message_params
#     params.require(:message).permit(:to, :from, :body)
#   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact.html.erb
  <p><%= link_to contact.name, contact %></p>
  <p><%= contact.phonenumber %></p>

app/views/contacts/_contact_show_tile.html.erb
<h2><%= @contact.name %></h2>
<p><%= @contact.phonenumber %></p>

app/views/contacts/_form.html.erb
<%= simple_form_for @contact, remote: true do |f| %>
    <%= f.error_notification %>
    <% if @contact.errors.any? %>
      <% @contact.errors.full_messages.each do |m| %>
      <div class='alert alert-danger'>
        <p><%= m %></p>
      </div>
      <% end %>
    <% end %>
  <div class="form-inputs form-group">
    <%= f.input :name %>
    <%= f.input :phonenumber %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Save Catact" %>
  </div>
<% end %>

app/views/contacts/create.js.erb
$("form").hide();
$("#new-contact").show();
$(".contacts-list").append("<%= j render(@contact) %>").prepend("<p class='alert alert-success'><%= flash[:notice] %></p>");

app/views/contacts/edit.js.erb
$("#update-contact").after("<%= j render('form') %>");
$("#update-contact").hide();

app/views/contacts/index.html.erb
<h1>Catacts</h1>

<p><%= link_to "Home", root_path %></p>
<p> <%= link_to "Add new Catact", new_contact_path, id: "new-contact", remote: true %></p>
<hr>
<div class="contacts-list">
  <%= render @contacts %>
</div>

app/views/contacts/new.js.erb
$("#new-contact").after("<%= j render('form') %>");
$("#new-contact").hide();

app/views/contacts/show.html.erb
<div class="contact-card">
  <%= render 'contact_show_tile', contact: @contact %>
</div>

<p><%= link_to "Update Catact", edit_contact_path(@contact), id: 'update-contact', remote: true  %></p>
<p><%= link_to "Back to All Catacts", contacts_path %></p>

app/views/contacts/update.js.erb
$("form").hide();
$("#update-contact").show();
$(".contact-card").html('<%= j render("contact_show_tile") %>').prepend("<p class='alert alert-success'><%= flash[:notice] %></p>");

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |m| %>
  <div class='alert alert-danger'>
    <p><%= m %></p>
  </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatFacts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% if notice %>
      <p class='alert alert-success'><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class='alert alert-danger'><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_tag (messages_path), remote: true do %>

  <div class="form-inputs form-group">
    <%= label_tag :to, 'To' %>
    <%= text_field_tag(:to, nil, class: 'form-control') %>
    <%= label_tag 'Or, select an existing contact:' %>
    <ul>
      <% @contacts.each do |contact| %>
        <li><%=label_tag contact.name  %>
        <%= check_box_tag "contact_ids[]", contact.id %></li>
      <% end %>
    </ul>
    <%= label_tag :from %>
    <%= text_field_tag(:from, "5412482591", class: 'form-control') %>
    <%= label_tag 'Cat Fact' %>
    <%= text_area_tag(:body, nil, class: 'form-control') %>
  </div>
  <div class="form-actions">
    <%= submit_tag "Send Cat Fact" %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<% if Contact.exists?(:phonenumber => message.to) %>
  <% contact = Contact.where(:phonenumber => message.to).take %>
    <li><%= link_to "To #{contact.name}, #{message.created_at.strftime('at %I:%M%p')}", message %></li>
  <% else %>
    <li><%= link_to "To #{message.to}, #{message.created_at.strftime('at %I:%M%p')}", message %></li>
<% end %>

app/views/messages/create.js.erb
$("form").hide();
$("#new-fact").show();
$(".messages-list").append("<%= j render(@message) %>").prepend("<p class='alert alert-success'><%= flash[:notice] %></p>");

app/views/messages/index.html.erb
<h1>Welcome to Cat Facts</h1>
<p><%= link_to "Send New Cat Fact", new_message_path, remote: true, id: 'new-fact' %></p>
<p><%= link_to "Contacts", contacts_path %></p>
<hr>
<h3>Sent Facts:</h3>
<ul class="messages-list">
  <%= render @messages %>
</ul>

app/views/messages/messages_sent.js.erb
location.reload();

app/views/messages/new.html.erb
<h1>Send a New Cat Fact</h1>

<%= render 'form' %>
<br>
<p><%= link_to "Home", root_path %></p>

app/views/messages/new.js.erb
$("#new-fact").after("<%= j render('form') %>");
$("#new-fact").hide();

app/views/messages/show.html.erb
<h2>Cat Fact sent <%= @message.created_at.strftime("at %I:%M%p") %>:</h2>

<h3>"<%= @message.body %>"</h3>

<%= link_to "Back to all Cat Facts", messages_path %>